#!/bin/bash
# little script for getting the repository all set up

# parse remote base from args
origin_base="git@github.com:kurotetsuka"
upstream_base="git@github.com:kurotetsuka"
[ $# -gt 0 ] && origin_base="$1"
[ $# -gt 1 ] && upstream_base="$2"
#echo "origin base: $origin_base"
#echo "upstream base: $upstream_base"
repos="\
	dttp \
	dttp-spec \
	hyphae \
	hyph-spec \
	hyphic \
	hyph-web"

# clone source repos
echo "cloning component repositories"
for repo in ${repos}; do
	git clone ${origin_base}/${repo} ${repo}
done

# add upstream remotes
echo "adding upstream remotes"
for repo in ${repos}; do
	( cd ${repo} && git remote add upstream ${upstream_base}/${repo} )
done
